### ISSUE TITLE
import model error

### ISSUE THREAD

**Issue by ryan715** [medcl/elasticsearch-rtf#53] opened 2016-12-06 05:03 UTC
when I run commands like 
```
rake environment elasticsearch:import:model CLASS=Topic FORCE=y
```

it gave eroor below:
```
Elasticsearch::Transport::Transport::Errors::BadRequest: [400] {"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"Failed to parse mapping [topic]: The [string] type is removed in 5.0 and automatic upgrade failed because parameters [term_vector] are not supported for automatic upgrades. You should now use either a [text] or [keyword] field instead for field [title]"}],"type":"mapper_parsing_exception","reason":"Failed to parse mapping [topic]: The [string] type is removed in 5.0 and automatic upgrade failed because parameters [term_vector] are not supported for automatic upgrades. You should now use either a [text] or [keyword] field instead for field [title]","caused_by":{"type":"illegal_argument_exception","reason":"The [string] type is removed in 5.0 and automatic upgrade failed because parameters [term_vector] are not supported for automatic upgrades. You should now use either a [text] or [keyword] field instead for field [title]"}},"status":400}
```

the model is 
```
 mapping do
    indexes :title, term_vector: :yes
    indexes :body, term_vector: :yes
    indexes :node_name
  end

  def as_indexed_json(_options = {})
    {
      title: self.title,
      body: self.full_body,
      node_name: self.node_name
    }
  end

  def related_topics(size = 5)
    opts = {
      query: {
        more_like_this: {
          fields: [:title, :body],
          docs: [
            {
              _index: self.class.index_name,
              _type: self.class.document_type,
              _id: id
            }
          ],
          min_term_freq: 2,
          min_doc_freq: 5
        }
      },
      size: size
    }
    self.class.__elasticsearch__.search(opts).records.to_a
  end
```

**Comment by medcl** [comment] 2017-10-10 10:47
hi，the error message is clear,please update the library you are using，the generated mapping is still for elasticsearch 2.x, the issue is not related with this project

**Comment by medcl** [comment] 2017-10-10 10:48
sorry for the late reply，closing now

**Closed by medcl** 2017-10-10 10:48 UTC
